spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: wkdalxpfl12!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# JWT 설정
jwt:
  secret: exceednewsecretkey12345678901234567890123456789012
  refresh-expiration: 1209600000 # 2주

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.blog.exceed.dao
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: INFO
    com.blog.exceed: DEBUG
    com.blog.exceed.mapper: DEBUG
    org.mybatis: DEBUG
    org.springframework.jdbc.core: TRACE
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE

ai:
  api:
    base-url: http://127.0.0.1:1234
    endpoints:
      models: /v1/models
      chat: /v1/chat/completions
      completions: /v1/completions

# RestTemplate 설정
rest-template:
  connection-timeout: 100000
  read-timeout: 100000 